trigger:
  branches:
    include: 
    - master
variables:
  buildConfiguration: 'Release'
  location: 'westeurope'
  acrHostName: 'keyifydockertest.azurecr.io'
  acrName: 'keyifydockertest'
  rgName: 'keyifydockertest'
  imageName: 'keyifydockertest-image'
  webAppName: 'keyifydockertest'

stages:

# Build Stage
- stage: BuildAndTest
  jobs:
  - job: BuildAndTest
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    
    - task: DotNetCoreCLI@2
      displayName: Restore All Projects
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        feedsToUse: 'select'

    - task: DotNetCoreCLI@2
      displayName: Build Keyify.Web
      inputs:
        command: 'build'
        projects: '**/Keyify.Web.csproj'
        arguments: '--configuration $(buildConfiguration) --no-restore'

    # - task: DotNetCoreCLI@2
    #   displayName: Restore Tests
    #   inputs:
    #     command: 'restore'
    #     projects: '**/*Test.csproj'
    #     feedsToUse: 'select'

    - task: DotNetCoreCLI@2
      displayName: Build Tests
      inputs:
        command: 'build'
        projects: '**/*Unit.Test.csproj'
        arguments: '--configuration $(buildConfiguration) --no-restore'
        
    # - task: DotNetCoreCLI@2
    #   displayName: Run Unit Tests
    #   inputs:
    #     command: 'test'
    #     projects: '**/*Unit.Test.dll'
    #     arguments: '--configuration $(buildConfiguration) --no-restore'
    #     testRunTitle: 'Run Tests'

    # - task: VSTest@3
    #   inputs:
    #     testSelector: 'testAssemblies'
    #     testAssemblyVer2: |
    #       **\*Unit.Test.dll
    #       !**\*TestAdapter.dll
    #       !**\obj\**
    #     searchFolder: '$(System.DefaultWorkingDirectory)'
    #     runOnlyImpactedTests: false

    - task: DotNetCoreCLI@2
      displayName: 'dotnet custom'
      inputs:
        command: custom
        projects: '**\*Unit.Test.dll'
        custom: vstest
        arguments: '--logger:trx;logfilename=TEST.xml'