trigger:
  branches:
    include: 
    - master
variables:
  buildConfiguration: 'Release'
  location: 'uksouth'
  rgName: 'notestokey'
  webAppName: 'notestokey'

stages:
- stage: BuildWindowsFilesAndTest
  displayName: Build Windows Files and Run Unit Test
  jobs:
  - job: BuildWindowsFilesAndTest
    displayName: Build Windows Files and Run Unit Test
    pool:
      vmImage: 'windows-latest'
    
    steps:
    - task: DotNetCoreCLI@2
      displayName: Restore Unit Tests
      inputs:
        command: 'restore'
        projects: '$(System.DefaultWorkingDirectory)\**\*Unit.Test.csproj'
    
    - task: DotNetCoreCLI@2
      displayName: Build Unit Tests
      inputs:
        command: 'build'
        projects: '$(System.DefaultWorkingDirectory)\**\*Unit.Test.csproj'
      
    - task: VSTest@3
      displayName: Run Unit Tests
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: |
          **\*test*.dll
          !**\*TestAdapter.dll
          !**\obj\**
          !**\testhost*.*
          !**\Microsoft*.dll
        searchFolder: '$(System.DefaultWorkingDirectory)'
        runOnlyImpactedTests: false
        
    - task: AzureKeyVault@2
      displayName: Retrieve Staging Database ConnectionString
      inputs:
        azureSubscription: 'campbe11sean root(c5d140d4-4130-4229-9fc9-025261099893)'
        KeyVaultName: 'DeploymentSecretsKeyify'
        SecretsFilter: 'stagingDatabaseConnectionString'
        RunAsPreJob: true
        
    - task: DotNetCoreCLI@2
      displayName: Restore Database Integration Tests
      inputs:
        command: 'restore'
        projects: '$(System.DefaultWorkingDirectory)\**\*Integration.Test.csproj'
        
    - task: DotNetCoreCLI@2
      displayName: Build Database Integration Tests
      inputs:
        command: 'build'
        projects: '$(System.DefaultWorkingDirectory)\**\*Integration.Test.csproj'
      
    - task: CmdLine@2
      inputs:
        script: |
          echo '$(stagingDatabaseConnectionString)'

    - task: PowerShell@2
      displayName: Set Database ConnectionString
      inputs:
        targetType: 'inline'
        script: | 
          Write-Host ("##vso[task.setvariable variable=databaseConnectionString]$(stagingDatabaseConnectionString)")

    - task: VSTest@3
      displayName: Run Integration Tests
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: |
          **\*Integration.Test*.dll
          !**\*TestAdapter.dll
          !**\obj\**
          !**\testhost*.*
          !**\Microsoft*.dll
        searchFolder: '$(System.DefaultWorkingDirectory)'
        runOnlyImpactedTests: false

# - stage: BuildAndCreateImage
#   displayName: Build and Create Image
#   jobs:
#   - job: BuildAndCreateImage
#     displayName: Build and Create Image
#     pool:
#       vmImage: 'ubuntu-latest'
#     steps:    
#     - task: DotNetCoreCLI@2
#       displayName: Restore All Projects
#       inputs:
#         command: 'restore'
#         projects: '**/*.csproj'
#         feedsToUse: 'select'

#     - task: DotNetCoreCLI@2
#       displayName: Build Keyify.Web
#       inputs:
#         command: 'build'
#         projects: '**/Keyify.Web.csproj'
#         arguments: '--configuration $(buildConfiguration) --no-restore'