trigger:
  branches:
    include: 
    - master
variables:
  buildConfiguration: 'Release'
  location: 'westeurope'
  acrHostName: 'keyifydockertest.azurecr.io'
  acrName: 'keyifydockertest'
  rgName: 'keyifydockertest'
  imageName: 'keyifydockertest-image'
  webAppName: 'keyifydockertest'

stages:
- stage: BuildWindowsFilesAndTest
  displayName: Build Windows Files and Run Unit Test
  jobs:
  - job: BuildWindowsFilesAndTest
    displayName: Build Windows Files and Run Unit Test
    pool:
      vmImage: 'windows-latest'
    
    steps:
    - task: DotNetCoreCLI@2
      displayName: Restore Unit Tests
      inputs:
        command: 'restore'
        projects: '**/*Unit.Test.csproj'
    - task: VSTest@3
      displayName: Run Unit Tests
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: |
          **\bin\$(BuildConfiguration)\**\*test*.dll
          !**\*TestAdapter.dll
          !**\obj\**
          !**\testhost*.*
          !**\Microsoft*.dll
        searchFolder: '$(System.DefaultWorkingDirectory)'
        runOnlyImpactedTests: false

- stage: BuildAndCreateImage
  displayName: Build and Create Image
  jobs:
  - job: BuildAndCreateImage
    displayName: Build and Create Image
    pool:
      vmImage: 'ubuntu-latest'
    steps:    
    - task: DotNetCoreCLI@2
      displayName: Restore All Projects
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        feedsToUse: 'select'

    - task: DotNetCoreCLI@2
      displayName: Build Keyify.Web
      inputs:
        command: 'build'
        projects: '**/Keyify.Web.csproj'
        arguments: '--configuration $(buildConfiguration) --no-restore'