trigger:
  branches:
    include:
      - master
    exclude:
    - feature/*
    - release/*

variables:
  buildConfiguration: 'Release'
  location: 'uksouth'
  rgName: 'notestokey'
  webAppName: 'notestokey2'
  scriptDirectory: '\\Keyify.Database.DbUp.Scripts'
  vmImageName: 'ubuntu-latest'

stages:
- stage: BuildLinuxTestFilesAndTest
  displayName: Build and Run Unit Tests
  jobs:
  - job: BuildLinuxTestFilesAndRunTests
    displayName: Build Linux Test Files and Run Unit Tests
    pool:
      vmImage: '$(vmImageName)'
    steps:

    - task: DotNetCoreCLI@2
      displayName: Build Unit Tests
      inputs:
        command: 'build'        
        projects: '$(System.DefaultWorkingDirectory)/**/*Unit.Test.csproj'

    - task: DotNetCoreCLI@2
      displayName: Run Unit Tests
      inputs:
        azureSubscription: 'campbe11sean root(c5d140d4-4130-4229-9fc9-025261099893)'
        command: 'test'
        projects: |
          **/*.Test.dll
          !**/*TestAdapter.dll
          !**/obj/**
          !**/testhost*.*
          !**/Microsoft*.dll
        testRunTitle: 'Run Unit Tests'

- stage: BuildAndDeployDbUp
  displayName: Database Deployments
  dependsOn: BuildLinuxTestFilesAndTest
  jobs:
  - job: BuildAndDeployDbUp
    displayName: Retrieve ConnectionString and Deploy Scripts via DbUp
    pool:
      vmImage: '$(vmImageName)'
    steps:
    - task: AzureKeyVault@2
      displayName: Retrieve Staging Database ConnectionString
      inputs:
        azureSubscription: 'campbe11sean root(c5d140d4-4130-4229-9fc9-025261099893)'
        KeyVaultName: 'DeploymentSecretsKeyify'
        SecretsFilter: 'stagingDatabaseConnectionString'
        RunAsPreJob: true

    - task: PowerShell@2
      displayName: Set Database ConnectionString
      inputs:
        targetType: 'inline'
        script: | 
          Write-Host ("##vso[task.setvariable variable=databaseConnectionString]$(stagingDatabaseConnectionString)")

    # - task: DotNetCoreCLI@2
    #   displayName: Restore DbUp Projects
    #   inputs:
    #     command: 'restore'
    #     projects: '$(System.DefaultWorkingDirectory)/**/Keyify.Database.DbUp*.csproj'

    - task: DotNetCoreCLI@2
      displayName: Build DbUp Project
      inputs:
        command: 'build'
        projects: '$(System.DefaultWorkingDirectory)/**/Keyify.Database.DbUp*.csproj'

    - task: DotNetCoreCLI@2
      displayName: Run DbUp Project
      inputs:
        azureSubscription: 'campbe11sean root(c5d140d4-4130-4229-9fc9-025261099893)'
        command: 'run'
        projects: '$(System.DefaultWorkingDirectory)/**/Keyify.Database.DbUp.csproj'
        arguments: '"$(stagingDatabaseConnectionString)" "$(scriptDirectory)"'
        
    - task: DotNetCoreCLI@2
      displayName: Restore RecordCreation Project
      inputs:
        command: 'restore'
        projects: '$(System.DefaultWorkingDirectory)/**/Keyify.Database.RecordCreation.csproj'

    - task: DotNetCoreCLI@2
      displayName: Build DbUp Project
      inputs:
        command: 'build'
        projects: '$(System.DefaultWorkingDirectory)/**/Keyify.Database.RecordCreation.csproj'

    - task: DotNetCoreCLI@2
      displayName: Run DbUp Project
      inputs:
        azureSubscription: 'campbe11sean root(c5d140d4-4130-4229-9fc9-025261099893)'
        command: 'run'
        projects: '$(System.DefaultWorkingDirectory)/**/Keyify.Database.RecordCreation.csproj'
        arguments: '"$(stagingDatabaseConnectionString)" "$(scriptDirectory)"'

- stage: BuildAndDeployWebApp
  displayName: Deploy Web Application
  dependsOn: BuildAndDeployDbUp
  jobs:
  - job: BuildAndDeployWebApp
    displayName: Deploy Web App
    pool:
      vmImage: '$(vmImageName)'
    steps:    
    - task: DotNetCoreCLI@2
      displayName: Build Keyify.Web
      inputs:
        command: 'build'
        projects: '**/Keyify.Web.csproj'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        projects: '$(System.DefaultWorkingDirectory)/**/*Web.csproj'
        publishWebProjects: true

    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'campbe11sean root(c5d140d4-4130-4229-9fc9-025261099893)'
        appType: 'webApp'
        appName: $(webAppName)
        resourceGroupName: $(rgName)
        package: '$(System.DefaultWorkingDirectory)/**/*.zip'