#Note: not sure this is doing anything

version: '3.4'

services:
  tomssl.app:
    image: ${DOCKER_REGISTRY-}keyify
    ports:
     - 80:80
     - 443:443
    build:
      context: .
      dockerfile: src/keyify/Dockerfile