CREATE TABLE [Core].[ScaleDefinition] (
	[Id] INT IDENTITY(0, 1) NOT NULL PRIMARY KEY,
	[Name] NVARCHAR(100) NOT NULL UNIQUE,
	[Description] NVARCHAR(100) NULL,
	[Intervals] VARBINARY(900) NOT NULL UNIQUE,
	[Degrees] VARBINARY(900) NOT NULL UNIQUE,
	[AllowedRootNotes] VARBINARY(900) NULL,
	[Created] DATETIME NOT NULL DEFAULT GETUTCDATE(),
	[LastModified] DATETIME NULL,
	[Deleted] BIT NOT NULL DEFAULT 0,
	[CreatedById] INT NOT NULL DEFAULT 0,
	CONSTRAINT [FK_ScaleDefinition_CreatedById] FOREIGN KEY ([CreatedById]) REFERENCES [Core].[User](Id)
	)
GO