CREATE TABLE [Core].[User] (
	[Id] INT IDENTITY(0, 1) NOT NULL PRIMARY KEY,
	[FirstName] NVARCHAR(200) NOT NULL,
	[Surname] NVARCHAR(300) NOT NULL,
	[EmailAddress] NVARCHAR(300) NOT NULL,
	[Created] DATETIME NOT NULL DEFAULT GETUTCDATE(),
	[LastModified] DATETIME NULL,
	[Deleted] BIT NOT NULL DEFAULT 0
	)
GO